apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "comax-central.secretName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "comax-central.serviceAccountName" . }}
data:
  CONNSTR: {{ .Values.connstr | b64enc }}
  CLIENT_SECRET: {{ .Values.central.secret | b64enc }}