apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "comax-accounts.certSecretName" . }}
spec:
  dnsNames:
  - {{ include "comax-accounts.fullSvcName" . }}
  {{- range .Values.ingress.tls }}
  {{- range .hosts }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: {{ include "comax-accounts.certSecretName" . }}
  usages:
  - digital signature
  - key encipherment