apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-accounts.fullname" . }}
  labels:
    {{- include "comax-accounts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "comax-accounts.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-central.fullname" . }}
  labels:
    {{- include "comax-central.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "comax-central.selectorLabels" . | nindent 4 }}
