using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OIDCClient.ViewModels.Authorize
{
    public class TokenViewModel
    {
        [Display(Name = "Challenge Code Generated by OIDC Server")]
        public string code { get; set; }
        [Display(Name = "Client Id")]
        public string clientId { get; set; }
        [Display(Name = "Secret")]
        public string secret { get; set; }
    }
}
