<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>CommunAxiom.Accounts.BusinessLayer</AssemblyName>
	  <RootNamespace>CommunAxiom.Accounts.BusinessLayer</RootNamespace>
	  <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\DatabaseFramework\DatabaseFramework.csproj" />
	  <PackageReference Include="RandomDataGenerator.Net" Version="1.0.17" />
	  <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>

</Project>
